spring.datasource.url=jdbc:postgresql://localhost:5432/app_db?sslmode=disable
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=9999